name: Build

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build on ${{ matrix.NAME }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            NAME: linux
          #- os: windows-latest
          #  NAME: windows
          #- os: macos-latest
          #  NAME: macos-x86-64
          #- os: [self-hosted, macOS, ARM64]
          #  NAME: macos-arm64
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "22.1.0"
          java-version: "11"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Install
        run: |
          mvn clean install

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: graalvm-test-native-lib-${{ matrix.NAME }}
          path: |
            target/native-image

# ToDo: Not actually work.
      - name: Create archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'graalvm-test-native-lib-${{ matrix.NAME }}.zip'
          directory: target/native-image
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/native-image/graalvm-test-native-lib-${{ matrix.NAME }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
